export const CREATE_CONTACT = "CREATE_CONTACT";
export const GET_CONTACT = "GET_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SELECTED_ALL = "SELECTED_ALL";
export const CLEAR_CONTACT = "CLEAR_CONTACT";
export const DELETE_ALL = "DELETE_ALL";
